function run_highlight_slider(b){var a=$(b+" li").length;if($.fn.cssOriginal!=undefined){$.fn.css=$.fn.cssOriginal}
$(b).samslider({delay:10000,startwidth:1366,startheight:503,onHoverStop:"on",navigationType:a>1?"both":"none",navigationArrows:a>1?"nexttobullets":"none",navigationStyle:"navigation",touchenabled:"on",navOffsetHorizontal:0,navOffsetVertical:0,fullWidth:"on",shadow:0})}
function run_slide(){run_highlight_slider(".fullwidthslide")}
function run_for_home(){run_slide();show_slide_explore();hide_slide_explore();activate_event_carousel();activate_promo_carousel();activate_hover_carousel();other_link_carousel();nav_slide_home();var a=[[{ID:"#news_cycle_home",PAGER:"#nav_cycle_news",TO:15000},{ID:"#slide_under_767",PAGER:"#nav_slide_under_767",TO:10000}]];run_cycle(a);$(".navigation").click(function(){$(".box_explore").fadeTo(300,0,function(){$(this).hide()});$(".show_explore").fadeTo(300,1)})}
function show_slide_explore(){$(".show_explore").click(function(a){a.preventDefault();$(this).fadeTo(100,1,function(){$(this).hide()});$("#"+$(this).attr("rel")).fadeTo(300,1);$(".explore_product_detail").css({opacity:1})})}
function hide_slide_explore(){$(".close_explore").click(function(a){a.preventDefault();$(".show_explore").fadeTo(300,1);$(".box_explore").fadeTo(300,0,function(){$(this).hide()})})}
function run_cycle(a){$.each(a,function(){$.each(this,function(){$(this["ID"]).cycle({fx:"scrollLeft",pager:this["PAGER"],timeout:this["TO"]})})})}
function run_for_profile(){var a;$(".list_profile").each(function(b){a=b+1;$(this).addClass("page_"+a).attr({name:$(this).find(".title_sub_page").text(),rel:"page"+a,id:"box_page"+a})});run_slide();activate_accordion("#sub_manufacturing");activate_accordion_duty("#sub_duty_news")}
function run_for_product(b){preload("#loader_compare,#loader_other");var a={URL:b.URL+"/slide-items/",TARGET:"#frame-car-banner"};load_view(a,"pid="+b.PID+"&cid="+b.CID);activate_car_exterior();activate_interior_pano();activate_box_features_thumbs("#box_home_features");switch_price_menu();switch_price_cover();activate_small_accordion();activate_big_accordion();$("#active_"+b.PID).addClass("active");if(b.TIPE=="dyna"){var c={URL:b.URL+"/"+b.TIPE+"/list-type/",TARGET:"#frame-list-type"};load_view(c,"")}}
function list_spec_dyna(f){var b={URL:f.URL+"/"+f.TIPE+"/list-spec/",TARGET:"#frame-list-spec"},g=new Array,d=new Array,a=new Array,c=$(".list_active");c.each(function(h){d[h]=$(this).width();a[h]=$(this).height()});d.sort(function(i,h){return h-i});a.sort(function(i,h){return h-i});c.height(a[0]);load_view(b,"l_active="+f.LACTIVE+"&w_="+d[0]);$(".dd_type li a").click(function(h){h.preventDefault();$("#"+$(this).parents("ul").attr("rel")).text($(this).text()).attr("rel",$(this).attr("rel"));c.each(function(i){g[i]=$(this).attr("rel")});load_view(b,"l_active="+g)})}
function run_for_product2(b){preload("#loader_compare");var a={URL:b.URL+"/slide-items/",TARGET:"#frame-car-banner"};load_view(a,"pid="+b.PID+"&cid="+b.CID);activate_car_exterior();activate_interior_pano();activate_box_features_thumbs("#box_home_features");switch_price_menu();switch_price_cover();activate_small_accordion();activate_big_accordion();$("#active_"+b.PID).addClass("active")}
function run_for_dyna_news(d,b,f){var c={URL:d+"/list-news/",TARGET:"#list-dyna-news"},a={URL:d+"/lates-news/",TARGET:"#view-lates-news"};load_view(a,"");load_view(c,"publish="+b+"&latesid="+f);$("#btn_action").click(function(){$("#form-filter").attr("action",d+"/"+$(this).attr("rev")+"/").submit()})}
function slide_banner_product(b){if(b.TIPE=="dyna"){var a={URL:b.URL+"/"+b.TIPE+"/list-gallery-dyna/",TARGET:"#list-gallery"}}else{var a={URL:b.URL+"/list-gallery/",TARGET:"#list-gallery"};var c={URL:b.URL+"/list-other/",TARGET:"#list-other-type"};load_view(c,"current_="+b.PID+"&cid="+b.CID)}
load_view(a,"pid="+b.PID+"&to=20");$(".img_vid_more a").click(function(e){e.preventDefault();var d=parseInt($(this).attr("href"));load_view(a,"pid="+b.PID+"&to="+(d+20));$(this).attr("href",d+20)});if(b.ROW>0){$("#banner_slide_product").responsiveSlides({auto:true,pager:true,nav:false,speed:1000,namespace:"callbacks",before:function(){$(".events").append("<li>before event fired.</li>")},after:function(){$(".events").append("<li>after event fired.</li>")}});$(".callbacks_tabs").appendTo(".nav_slide")}}
function compare_other_type(b){activate_sub_small_accordion();$(b.HANDLER).trigger("click");var a={URL:b.URL+"/set-compare/",TARGET:"#list-other-type"};if(b.CNUM<2){$(".type-other a").click(function(c){c.preventDefault();load_view(a,"cid="+b.CID+"&pid="+$(this).attr("rel"))});$("a.current").trigger("click")}else{$(".type-other a").css({cursor:"default"})}}
function list_td_spec(b){activate_spec_accordion();var a={URL:b.URL+"/set-compare/",TARGET:"#list-other-type"},c={URL:b.URL+"/list-other/",TARGET:"#list-other-type"};load_view(c,"pid="+b.PID+"&cid="+b.CID);$(".prp_table_head td:last-child").css({"border-left":"1px solid #ddd"});$(".prp_content_accordion_ctn td:last-child").css({"border-left":"1px solid #ddd"});$(".prp_table_head td").each(function(d){$(".table_compare tr td:nth-child("+(d+1)+")")});$(".close_compare").click(function(){load_view(a,"tipe=close&cid="+b.CID+"&pid="+$(this).attr("rel"))})}
function gallery_product_dyna(){var b=$(window).width();var a=940;if(b<940){a=b}
$(".img_vid_list").AutoImage({width:a,height:1000,caption:false,captionOnMouseOver:true,anchorVertical:"middle",anchorHorizontal:"center",callback:fancybox_gallery});var c;$(window).resize(function(){clearTimeout(c);c=setTimeout("view_changed_gallery()",150)})}
function gallery_product(){var b=$(window).width();var a=940;if(b<940){a=b}
$(".img_vid_list").AutoImage({width:a,height:1000,caption:false,captionOnMouseOver:true,anchorVertical:"middle",anchorHorizontal:"center",callback:fancybox_gallery});var c;$(window).resize(function(){clearTimeout(c);c=setTimeout("view_changed_gallery()",150)})}
function preload(a){$(a).ajaxStart(function(){$(this).show()}).ajaxStop(function(){$(this).hide()})}
function width_gallery_product(){var a=$(".img_vid").width();$(".img_vid_list").each(function(){$(this).width(a)})}
function run_for_ebrochure(b){run_slide();var a={URL:b+"/list-brochure/",TARGET:"#list-brochure"};load_view(a,"")}
function run_for_manual(b){var a={URL:b+"/list-manual/",TARGET:"#list-manual"};load_view(a,"")}
function set_list_ebrochure(){var a=new Array;$(".link_list").each(function(b){a[b]=$(this).height()});a.sort(function(c,b){return b-c});$(".link_list").height(a[0])}
function set_list_manual(){var a=new Array;$(".link_list").each(function(b){a[b]=$(this).height()});a.sort(function(c,b){return b-c});$(".link_list").height(a[0])}
function view_changed_gallery(){width_gallery_product()}
function set_td_width_compare_product(){var b=$(".pil_car_box").width();var a=$(".title_second_td").width();var c=$(".title_third_td").width();$(".table_compare_specification tr td:nth-child(2)").each(function(){$(this).width(b)});$(".table_compare_specification tr td:nth-child(1)").each(function(){$(this).width(200)})}
function run_for_faq(c){set_caption();run_slide();var a=1;$(".btn_show_hide_category_faq").click(function(f){f.preventDefault();if(a==0){$(this).removeClass("active");$(".list_category").stop().slideDown(500);a=1}else{if(a==1){$(this).addClass("active");$(".list_category").stop().slideUp(500);a=0}}});var d={URL:c+"/list-items/",TARGET:"#frame-list-faq"};load_view(d,"pid=");var b=$("ul.list_category li:nth-child(2) a");b.addClass("cat_active");if($("ul.list_category li:nth-child(2) a").attr("name")!=undefined&&$("ul.list_category li:nth-child(2) a").attr("name")!=""){window.location.hash=$("ul.list_category li:nth-child(2) a").attr("name");set_doc_title($("ul.list_category li:nth-child(2) a").attr("name"));set_google_analytics()}
$("ul.list_category a").click(function(f){f.preventDefault();$(".list_category a").removeClass("cat_active");$(this).addClass("cat_active");load_view(d,"pid="+$(this).attr("href"));if($(this).attr("name")!=undefined&&$(this).attr("name")!=""){window.location.hash=$(this).attr("name");set_doc_title($(this).attr("name"));set_google_analytics()}});b.trigger("click")}
function run_for_concept_car(b){set_caption();var a=1;$(".btn_show_hide_category_faq").click(function(d){d.preventDefault();if(a==0){$(this).removeClass("active");$(".list_category").stop().slideDown(500);a=1}else{if(a==1){$(this).addClass("active");$(".list_category").stop().slideUp(500);a=0}}});var c={URL:b+"/list-items/",TARGET:"#frame-list-faq"};load_view(c,"pid=");$("ul.list_category li:nth-child(1) a").addClass("cat_active");if($("ul.list_category li:nth-child(1) a").attr("name")!=undefined&&$("ul.list_category li:nth-child(1) a").attr("name")!=""){window.location.hash=$("ul.list_category li:nth-child(1) a").attr("name");set_doc_title($("ul.list_category li:nth-child(1) a").attr("name"));set_google_analytics()}
$("ul.list_category a").click(function(d){d.preventDefault();$(".list_category a").removeClass("cat_active");$(this).addClass("cat_active");load_view(c,"pid="+$(this).attr("href"));if($(this).attr("name")!=undefined&&$(this).attr("name")!=""){window.location.hash=$(this).attr("name");set_doc_title($(this).attr("name"));set_google_analytics()}});$("ul.list_category li:nth-child(1) a").trigger("click")}
function run_for_pricelist(b){set_caption();fly_pricelist();run_slide();var a={URL:b+"/data-price-list/",TARGET:"#frame-price-list"},c={URL:b+"/list-car/",TARGET:"#list-car"};load_view(c,"");load_view(a,"pid=")}
function price_list_car(b){$(".jqtransform").jqTransform();var a={URL:b,TARGET:"#frame-price-list"};$(".jqTransformSelectWrapper ul li a").click(function(){load_view(a,"pid="+$(this).attr("rel"))})}
function run_for_true_friend(b){set_caption();var a={URL:b+"/toyota-club/list-club/",TARGET:"#club_list"},c={URL:b+"/education-media/list-education-media/",TARGET:"#list-education-media"},e={URL:b+"/video/list-how-to-video/",TARGET:"#list-how-to-video"};load_view(a,"");load_view(c,"");load_view(e,"");}
function set_caption(){var a=$(".rm");$("#get_caption").text(a.text());a.remove()}
function fly_for_panelsub(){var a;if($("#box_submenu_page").html()!=null){a=1}else{a=0}
$("#box_main_menu").attr({rel:a})}
function run_for_csr(c){$(".page_area .box_waypoint").each(function(){var e=$(this).attr("rev");var f={URL:c+"/list-csr/",TARGET:"#frame-list-csr-"+e};load_view(f,"pid="+e)});var a={URL:c+"/list-programs/",TARGET:"#frame-list-programs"},d={URL:c+"/list-community/",TARGET:"#frame-list-community"},b={URL:c+"/list-news/",TARGET:"#frame-list-news"};load_view(a,"");load_view(d,"");load_view(b,"");run_slide()}
function tabs_content(c,a){var d=$("#submenu li a:first"),b={URL:c+"/list-csr/",TARGET:"#frame-content-tab"};d.addClass("active");load_view(b,"url="+c+"&pid="+d.attr("href").replace("#","")+"&rid="+a);$("#submenu li a").click(function(e){e.preventDefault();$("#submenu li a").removeClass("active");$(this).addClass("active");load_view(b,"url="+c+"&pid="+$(this).attr("href").replace("#","")+"&rid="+a)})}
function run_for_comparison(f){run_slide();set_caption();var b=$("#car_list li"),g;$(".list_type").find("input:checkbox").change(function(){var h=new Array;b.addClass("disabled").fadeTo(200,0.1);$(".list_type input:checked").each(function(e){h[e]=".compare_"+$(this).val()});if(h.toString()){$(h.toString()).removeClass("disabled").stop(false).fadeTo(200,1)}else{b.removeClass("disabled").stop(false).fadeTo(200,1)}});b.find("input:checkbox").change(function(){g=new Array,car_li_chk=b.find("input:checked");car_li_chk.each(function(h){g[h]=h});if(g.length>=3){b.addClass("disabled");if(car_li_chk.length>0){car_li_chk.parents("li").removeClass("disabled")}}else{b.removeClass("disabled")}});var d=["jquery.ui.core","jquery.ui.widget","jquery.ui.mouse","jquery.ui.slider"];$.each(d,function(){$("head").append('<script type ="text/javascript" src="'+f+"/ui/"+this+'.js"><\/script>')});var a=new Array,c=new Array;b.each(function(h){a[h]=$(this).attr("data-seats");c[h]=$(this).attr("data-power")});a.sort(function(i,h){return i-h});c.sort(function(i,h){return i-h});$(".slider").each(function(h){var i=$(this);if(h==0){i.attr({min:a[0],max:a[a.length-1]})}else{i.attr({min:c[0],max:c[c.length-1]})}
i.slider({range:true,min:0,max:i.attr("max"),values:[0,i.attr("max")],slide:function(k,j){i.find("a:first").text(j.values[0]);i.find("a:last").text(j.values[1]);b.addClass("disabled").fadeTo(200,0.1);b.each(function(p){var m=parseInt($(this).attr("data-seats")),q=parseInt($(this).attr("data-power")),l=parseInt(j.values[0]),o=parseInt(j.values[1]);if(m>=l&&m<=o||q>=l&&q<=o){$(this).removeClass("disabled").stop(false).fadeTo(200,1)}else{$(this).addClass("disabled").stop(false).fadeTo(200,0.1)}})}});i.find("a:first").text(i.slider("values",0));i.find("a:last").text(i.slider("values",1))});$(".btn_compare_product").css({cursor:"pointer"}).click(function(){if(g.length>1){$("#get_compare").submit()}})}
function run_for_tag_news(b){var a={URL:b.URL,TARGET:"#frame-list-tag"};load_view(a,"title="+b.TITLE)}
function run_for_after_sales(f,b,g){$(".rm").remove();run_slide();var d={URL:f+"/list-ownership-as/",TARGET:"#frame-list-ownership-as"},a={URL:f+"/lates-ownership-as/",TARGET:"#view-lates-ownership-as"},c=$("#submenu li a:first");load_view(a,"");}
function run_for_dyna_after_sales(d,b,f){var c={URL:d+"/list-after-sales/",TARGET:"#list-dyna-after-sales"},a={URL:d+"/lates-after-sales/",TARGET:"#view-lates-after-sales"};load_view(a,"");load_view(c,"latesid="+b)}
function run_for_news_promo(g,c,j,f){var k={URL:g+"/list-blog/",TARGET:"#frame-list-blog"},b={URL:g+"/list-promo/",TARGET:"#frame-list-promo"},d={URL:g+"/list-news/",TARGET:"#frame-list-news"},h={URL:g+"/lates-news/",TARGET:"#view-lates-news"},a=$("#submenu li a:first");load_view(h,"");load_view(b,"publish="+c);load_view(k,"publish="+c);a.addClass("active");load_view(d,"publish="+c+"&latesid="+j+"&catid="+a.attr("href").replace("#",""));$("#btn_action").attr("rev","tab-1");$("#submenu li a").click(function(i){i.preventDefault();$("#btn_action").attr("rev",$(this).attr("id"));$("#submenu li a").removeClass("active");$(this).addClass("active");load_view(d,"publish="+c+"&latesid="+j+"&catid="+$(this).attr("href").replace("#",""))});$("#btn_action").click(function(){$("#form-filter").attr("action",g+"/"+$(this).attr("rev")+"/").submit()});if(f){$(f).trigger("click")}}
function load_items_dealer(c){run_slide();var a=$("#p_city select");a.addClass("text_form");var d={URL:c,TARGET:"#dealer_box"},b;$(".btn_search_dealer").click(function(){if($("#txt_search_dealer").val()!=""){b="&p_key_dealer="+$("#txt_search_dealer").val()}else{b=""}
load_view(d,"p_city_dealer="+a.val()+b)});$("#txt_search_dealer").keyup(function(g){var f=g.keyCode?g.keyCode:g.which;if(f==13){if($(this).val()!=""){b="&p_key_dealer="+$(this).val()}else{b=""}
load_view(d,"p_city_dealer="+a.val()+b)}});$(".jqTransformSelectWrapper ul li a").click(function(){$("#jdl-list-dealer").text($(this).text());if($("#txt_search_dealer").val()!=""){b="&p_key_dealer="+$("#txt_search_dealer").val()}else{b=""}
load_view(d,"p_city_dealer="+a.val()+b)})}
function load_compare_car(b){activate_accordion_career("#compare_specification_box");var a={URL:b,TARGET:"#compare_specification_box"},c=new Array;$(".pil_car_box select").each(function(d){c[d]=$(this).find("option:nth-child(2)").val()});load_view(a,"caref="+c.toString());$(".jqTransformSelectWrapper ul li a").click(function(){var d=new Array;$(".jqTransformSelectWrapper select").each(function(e){if($(this).val()){d[e]=$(this).val()}else{d[e]=$(this).find("option:nth-child(2)").val()}});load_view(a,"caref="+d.toString())})}
function fancybox_gallery(){window.fbAsyncInit=function(){FB.init({appId:app_id,status:true,cookie:true,xfbml:true})};(function(d,b){var f,c="facebook-jssdk",a=d.getElementsByTagName("script")[0];if(d.getElementById(c)){return}
f=d.createElement("script");f.id=c;f.async=true;f.src="//connect.facebook.net/en_US/all"+(b?"/debug":"")+".js";a.parentNode.insertBefore(f,a)})(document,false);window.___gcfg={lang:"en-US"};(function(){var b=document.createElement("script");b.type="text/javascript";b.async=true;b.src="https://apis.google.com/js/plusone.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)})();$(".fancybox").attr("data-fancybox-group","gallery").fancybox({beforeLoad:function(){var m=window.location;var w=this.title.split("-"),g=this.href,b=this.type;var j='<a id="share-facebook" accept="'+b+'" rev="'+w[0]+"|"+w[1]+"|"+g+'" onClick="share_fb(this)"></a>',x='<a id="share-twitter" accept="'+b+'"  rev="'+w[0]+"|"+w[1]+"|"+g+'" onClick="share_twitter(this)"></a>',d='<a id="email" rev="'+w[2]+'" onClick="send_email(this)"></a>';if(b=="image"){var v=m.protocol+"//"+m.host+"/download/"+m.pathname.split("/")[1],q="gallery-share",k="image",h='<a id="download" href="'+v+"/"+w[2]+'/" target="frame-target"></a>',p='<a id="share-gplus" href="https://plus.google.com/u/0/share?url='+m.protocol+"//"+m.host+"/share/gplus/image/"+w[2]+"/\" onclick=\"javascript:window.open(this.href,'','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;\" ></a>"}else{if(b=="iframe"){var p='<a id="share-gplus" href="https://plus.google.com/u/0/share?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D'+g.split("embed/")[1].split("?")[0]+"%26feature%3Dshare&source=y/\" onclick=\"javascript:window.open(this.href,'','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;\" ></a>",q="gallery-video-share",h="",k="video"}}
this.title='<div class="'+q+'">'+j+x+p+d+h+"</div> "+(w[0]?w[0]:w[1])}})}
function send_email(b){var a=window.location;window.open(a.protocol+"//"+a.host+"/email/"+a.pathname.split("/")[1]+"/"+b.getAttribute("rev")+"/","send_email","width=330,height=300");return false}
function share_fb(f){var b=window.location,h=f.getAttribute("rev").split("|"),d=f.getAttribute("accept");if(d=="image"){var a=b.protocol+"//"+b.host+h[2]+"?v="+Math.random(),c=h[0]?h[0]:h[1],g=h[1]?h[1]:document.URL;FB.ui({method:"feed",display:"popup",name:"TOYOTA INDONESIA : "+c.toUpperCase(),caption:" ",description:g,link:document.URL,picture:a})}else{if(d=="iframe"){window.open("http://www.facebook.com/sharer/sharer.php?u="+b.protocol+"//"+b.host+"/share/"+h[2].split("embed/")[1].split("?")[0]+"/fb/video/","toyotasharefacebook","width=600,height=300")}}
return false}
function get_short_url(c,a,d,b){$.getJSON("http://api.bitly.com/v3/shorten?callback=?",{format:"json",apiKey:d,login:a,longUrl:c},function(f){b(f.data.url)})}
function share_twitter(g){var c="samdesign";var j="R_43be771e863224b95d9aff0f630e9416";var f=window.location,b=g.getAttribute("rev").split("|"),d=g.getAttribute("accept"),h=f.protocol+"//"+f.host,a;if(d=="image"){get_short_url(document.URL,c,j,function(i){window.open("https://twitter.com/intent/tweet?text="+(b[0]?b[0]:b[1])+"&url="+i+"&via=toyotaID","toyotasharetwitter","width=600,height=300")})}else{if(d=="iframe"){document.getElementById("twitframe").src=h+"/share/"+b[2].split("embed/")[1].split("?")[0]+"/twitter/video/"}}
return false}
function set_td_comparison(){var a=243;$(".table_compare_specification tr td:nth-child(4)").each(function(){$(this).width(a)});$(".table_compare_specification tr td:nth-child(3)").each(function(){$(this).width(a)});$(".table_compare_specification tr td:nth-child(2)").each(function(){$(this).width(a)});$(".table_compare_specification tr td:nth-child(1)").each(function(){$(this).width(312)})}
function load_items_car(b,a){var c={URL:b+"/items/",TARGET:".selected_car_comparison_box"};load_view(c,"pid="+a+"&url="+b)}
function load_compare_detail(a){preload("#loader_comparison");activate_accordion_career("#compare_specification_box");fly_comparation();run_slide();load_items_car(a.URL,a.PID)}
function run_for_pressroom(b){set_caption();var a={URL:b.URL+"/list/",TARGET:"#frame-list"},c={URL:b.URL+"/list-detail/",TARGET:"#gallery-detail-list"};if(b.TYPE=="PRESS-RELEASE"){load_view(a,"")}else{if(b.TYPE=="GALLERY"){if(b.PID){load_view(c,"to=20&pid="+b.PID);$(".img_vid_more a").click(function(d){d.preventDefault();var e=parseInt($(this).attr("href"));load_view(c,"to="+(e+20)+"&pid="+b.PID);$(this).attr("href",e+20)})}else{load_view(a,"")}}}}
function run_for_booking_service(d,b){var f=$("#p_city select"),c={URL:d+"/list-address/",TARGET:"#list-alamat"},a={URL:d+"/list-tanggal/",TARGET:"#list-tanggal"};$(".number").inputInteger();set_caption();run_slide();$("#p_city").change(function(){load_view(c,"pid="+f.val()+b)});load_view(c,"pid="+f.val()+b);$("#bulan").change(function(){load_view(a,"")})}
function view_img_car(b){$(".jqtransform").jqTransform();var a={URL:b+"/view-car/",TARGET:"#img_car"};$(".jqTransformSelectWrapper ul li a").click(function(){load_view(a,"pid="+$("#p_car").val());if($("#p_car").val()){$(".step2").find(".innactive").hide()}else{$(".legal_disclaimer").hide();$(".step2,.step3").find(".innactive").show()}})}
function next_step(){$("#next_step1").click(function(){if($("#p_nama_d").val()&&$("#p_email").val()&&$("#p_telp").val()){$(".step3").find(".innactive").hide()}})}
function run_list_view(){$(".nav_pagination_box a").click(function(){var a={URL:$(this).attr("rel"),TARGET:$(this).attr("rev")};load_view(a,"")});run_viewport()}
function set_clearfix(b){var a='<div class="clear_fix"> </div>';$(b+" li").each(function(c){if(window.innerWidth<939){if(c%2==1){$(a).insertAfter(this)}}else{if(c%3==2){$(a).insertAfter(this)}}})}
function run_viewport(){$(".box_page_area img").load_invewport({threshold:20,effect:"fadeIn"})}
function load_view(b,a){$.ajax({url:b.URL,type:"POST",cache:false,data:a,dataType:"html",success:function(c){$(b.TARGET).html(c)}})}
function run_for_all(){activate_accordion_content(".accordion_content");$(".img_cycle_content").cycle({fx:"scrollLeft",pager:"nextnya",timeout:5000})};function isEmail(email){var regex=/^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;return regex.test(email);}
function run_for_preorder(b,a){set_caption();$(".number").inputInteger();var c={URL:b+"/list-car/",TARGET:"#list-car"};run_slide();load_view(c,"url="+b+"&carid="+a);$("#next_step2").click(function(){var f=$("#p_city select").val(),d=$("#p_dealer").val();var g=$('#p_car').val(),h=$("#p_nama_d").val(),j=$("#p_nama_b").val(),k=$("#p_email").val(),l=$("#p_telp").val();if(f!=""&&d!=""&&g!=""&&h!=""&&j!=""&&k!=""&&l!=""){$(".legal_disclaimer").show();}else{if(!g){alert('Car must be field.');}else if(!h){alert('Nama depan must be field.');}else if(!k){alert('Email must be field.');}else if(!isEmail(k)){alert('Email format not match.');}else if(!l){alert('Telpone must be field.');}else if(!f){alert('Kota must be field.');}else if(!d){alert('Dealer must be field.');}}});$("#btn_action").click(function(){if($("#chbox").attr("checked")=="checked"){$("#send-request").submit()}})}
function load_view_preload(b,a,d){$(document).ajaxStart(function(){$(b.TARGET).hide();$(d).show();});$.ajax({url:b.URL,type:"POST",cache:false,data:a,dataType:"html",success:function(c){$(b.TARGET).html(c);$(d).hide();$(b.TARGET).show();}})};function load_view_loading(b,a,d){$(b.TARGET).hide();$(d).show();$.ajax({url:b.URL,type:"POST",cache:false,data:a,dataType:"html",success:function(c){$(b.TARGET).html(c);$(d).hide();$(b.TARGET).show();}})};