var window_width=$(window).width();$(document).ready(function(){var show_search=0;var show_connect=0;var search_width;if(window_width>810){search_width="660px";}else if(window_width<500&&window_width>400){search_width="200px";}else if(window_width<400){search_width="110px";}else{search_width="377px";}
$(".btn_show_search").click(function(e){e.preventDefault();if(show_search==0){$(".search_area").show();$(".textform").stop().animate({width:search_width,'padding-left':'10px'},100);$(this).css({'background-position':'bottom left'});show_search=1;$("#connect").hide();show_connect=0;}else if(show_search==1){$(".textform").stop().animate({width:"0px",'padding-left':'0'});$(".search_area").hide();$(this).css({'background-position':'top left'});show_search=0;}});$(".btn_show_connect1").click(function(e){e.preventDefault();if(show_connect==0){$("#connect").show();$(this).css({'background-position':'bottom left'});show_connect=1;}else if(show_connect==1){$("#connect").hide();$(this).css({'background-position':'top left'});show_connect=0;}});if(window_width>400){click_my_banner();intervalId=setInterval("slide_my_banner()",5000);}
$(".click_interior_360").click(function(e){e.preventDefault();$(".magic_container").stop().animate({top:"-435px"},300);});$(".show_all_price").click(function(e){e.preventDefault();$(".pricelist_box").show();});$("..pr_price_details .pricelist_box .ld_close_box").click(function(e){e.preventDefault();$(".pricelist_box").hide();});});function cat_list_home_1(){var handler=$('.info_list_1 li');handler.wookmark({autoResize:true,container:$('.main_1'),offset:20});handler.wookmark();}
function cat_list_home_2(){var handler=$('.info_list_2 li');handler.wookmark({autoResize:true,container:$('.main_2'),offset:20});handler.wookmark();}
function cat_list_home_3(){var $list=$('#category_list'),$items=$list.find('.category_text'),setHeights=function()
{$items.css('height','auto');var perRow=Math.floor($list.width()/$items.width());if(perRow==null||perRow<2)return true;for(var i=0,j=$items.length;i<j;i+=perRow)
{var maxHeight=0,$row=$items.slice(i,i+perRow);$row.each(function()
{var itemHeight=parseInt($(this).outerHeight());if(itemHeight>maxHeight)maxHeight=itemHeight;});$row.css('height',maxHeight);}};setHeights();$(window).on('resize',setHeights);$list.find('img').on('load',setHeights);}
function fixed_news(){var box_header_height=$(".box_header").height();var box_slide_height=$(".box_slide").height();var detail_news_height=$(".detail_news_text").height();var box_submenu_page_height=$(".box_submenu_page").height();var title_sub_page_height=$(".title_sub_page").height();var total_height=detail_news_height-100;if(window_width>=900){$(window).scroll(function(){detect_scroll=$(window).scrollTop();if(detect_scroll>total_height){$(".latest_news_fix").stop().animate({'right':'-3px'},100);}else{$(".latest_news_fix").stop().animate({'right':'-305px'},100);}})}
$(".close_fix_news").click(function(e){e.preventDefault();$(".latest_news_fix").stop().animate({'right':'-305px'},100);$(".latest_news_fix").hide();});}
var banner_state=1;var intervalId=0;function slide_my_banner(){curent_banner=banner_state;if(curent_banner<4){next_banner=curent_banner+1}
else{next_banner=1;}
$("#pil_banner a").removeClass("active");$("#pil_banner a:nth-child("+next_banner+")").addClass("active");$("#cycle_banner li:visible").fadeTo(0,0,function(){$(this).hide();$("#cycle_banner li:nth-child("+next_banner+")").fadeTo(0,1);});banner_state=next_banner;}
function click_my_banner(){$("#cycle_banner li").hide();$("#cycle_banner li:first").show();$("#pil_banner a").click(function(e){e.preventDefault();var nilai_banner=parseInt($(this).attr("rel"));$(this).siblings().removeClass("active");$(this).addClass("active");banner_state=nilai_banner;$("#cycle_banner li:visible").fadeTo(0,0,function(){$(this).hide();$("#cycle_banner li:nth-child("+nilai_banner+")").fadeTo(0,1);});clearInterval(intervalId);intervalId=setInterval("slide_my_banner()",5000);});}
function subject_info(){var strIndex=document.getElementById("select_subject").selectedIndex;$(".form_info_"+strIndex).show();$(".jqTransformSelectWrapper ul li a").click(function(e){e.preventDefault();$(".form_info div").hide();var strIndex=document.getElementById("select_subject").selectedIndex;$(".form_info_"+strIndex).show();});}